server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      #要绑定rabbitmq的服务信息
      binders:
        defaultRabbit:  #表示定义的名称，用于binding整合
          type: rabbit  #消息组件类型
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: WFXSWL/arPelu3RraGpLajAyK4QB8k9rJQNzHnUcwIKvCJC5AUH10y0XtZDyiysq2tUTL8XSWL
      bindings:
        input: #通道的名称
          destination: studyExchange  #表示使用exchange名称定义
          content-type: application/json  #设置消息类型，文本为text/plain
          binder: defaultRabbit #设置具体的绑定
          group: HelloA

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳间隔，默认30秒
    lease-expiration-duration-in-seconds: 5 #监控的时间，默认是90秒
    instance-id: receive-8802.com
    prefer-ip-address: true #显示服务的ip地址

jasypt:
  encryptor:
    bean: wfEncryptorBean
    property:
      prefix: WFXSWL
      suffix: XSWL
